export const COMPONENT_NAMES = {
  // Layout components
  LAYOUT: 'Layout',
  HEADER: 'Header',
  FOOTER: 'Footer',
  NAVBAR: 'Navbar',
  SIDEBAR: 'Sidebar',

  // Home page components
  HERO: 'Hero',
  FEATURES: 'Features',
  FEATURE_CARD: 'FeatureCard',
  PARTNERS: 'Partners',
  VIDEO_SECTION: 'VideoSection',
  APP_SHOWCASE: 'AppShowcase',
  TESTIMONIALS: 'Testimonials',
  CALL_TO_ACTION: 'CallToAction',
  ILLUSTRATION_SECTION: 'IllustrationSection',

  // Common components
  ANIMATION_WRAPPER: 'AnimationWrapper',
  ANIMATED_BUTTON: 'AnimatedButton',
  ANIMATED_LINK: 'AnimatedLink',
  ANIMATED_IMAGE: 'AnimatedImage',
  ANIMATED_TEXT: 'AnimatedText',
  ANIMATED_HEADING: 'AnimatedHeading',
  ANIMATED_PARAGRAPH: 'AnimatedParagraph',
  ANIMATED_LIST: 'AnimatedList',
  ANIMATED_LIST_ITEM: 'AnimatedListItem',
  ANIMATED_CARD: 'AnimatedCard',
  ANIMATED_CARD_CONTENT: 'AnimatedCardContent',
  ANIMATED_CARD_HEADER: 'AnimatedCardHeader',
  ANIMATED_CARD_TITLE: 'AnimatedCardTitle',
  ANIMATED_CARD_DESCRIPTION: 'AnimatedCardDescription',
  ANIMATED_CARD_FOOTER: 'AnimatedCardFooter',
  ANIMATED_CARD_IMAGE: 'AnimatedCardImage',
  ANIMATED_CARD_OVERLAY: 'AnimatedCardOverlay',
  ANIMATED_CARD_BADGE: 'AnimatedCardBadge',
  ANIMATED_CARD_TAG: 'AnimatedCardTag',
  ANIMATED_CARD_META: 'AnimatedCardMeta',
  ANIMATED_CARD_STATS: 'AnimatedCardStats',
  ANIMATED_CARD_ACTIONS: 'AnimatedCardActions',
  ANIMATED_CARD_ICON: 'AnimatedCardIcon',
  ANIMATED_CARD_AVATAR: 'AnimatedCardAvatar',
  ANIMATED_CARD_STATUS: 'AnimatedCardStatus',
  ANIMATED_CARD_PROGRESS: 'AnimatedCardProgress',
  ANIMATED_CARD_CHART: 'AnimatedCardChart',
  ANIMATED_CARD_TIMELINE: 'AnimatedCardTimeline',
  ANIMATED_CARD_GALLERY: 'AnimatedCardGallery',
  ANIMATED_CARD_CAROUSEL: 'AnimatedCardCarousel',
  ANIMATED_CARD_TABS: 'AnimatedCardTabs',
  ANIMATED_CARD_ACCORDION: 'AnimatedCardAccordion',
  ANIMATED_CARD_MODAL: 'AnimatedCardModal',
  ANIMATED_CARD_DRAWER: 'AnimatedCardDrawer',
  ANIMATED_CARD_POPOVER: 'AnimatedCardPopover',
  ANIMATED_CARD_TOOLTIP: 'AnimatedCardTooltip',
  ANIMATED_CARD_MENU: 'AnimatedCardMenu',
  ANIMATED_CARD_DROPDOWN: 'AnimatedCardDropdown',
  ANIMATED_CARD_CONTEXT_MENU: 'AnimatedCardContextMenu',
  ANIMATED_CARD_COMMAND: 'AnimatedCardCommand',
  ANIMATED_CARD_COMBOBOX: 'AnimatedCardCombobox',
  ANIMATED_CARD_SELECT: 'AnimatedCardSelect',
  ANIMATED_CARD_RADIO_GROUP: 'AnimatedCardRadioGroup',
  ANIMATED_CARD_CHECKBOX: 'AnimatedCardCheckbox',
  ANIMATED_CARD_SWITCH: 'AnimatedCardSwitch',
  ANIMATED_CARD_SLIDER: 'AnimatedCardSlider',
  ANIMATED_CARD_SPINNER: 'AnimatedCardSpinner',
  ANIMATED_CARD_SKELETON: 'AnimatedCardSkeleton',
  ANIMATED_CARD_PLACEHOLDER: 'AnimatedCardPlaceholder',
  ANIMATED_CARD_ERROR: 'AnimatedCardError',
  ANIMATED_CARD_SUCCESS: 'AnimatedCardSuccess',
  ANIMATED_CARD_WARNING: 'AnimatedCardWarning',
  ANIMATED_CARD_INFO: 'AnimatedCardInfo',
  ANIMATED_CARD_ALERT: 'AnimatedCardAlert',
  ANIMATED_CARD_TOAST: 'AnimatedCardToast',
  ANIMATED_CARD_NOTIFICATION: 'AnimatedCardNotification',
} as const; 